language: node_js
node_js:
- '6'
addons:
  apt:
    packages:
      - xvfb
install:
    - npm install -g xvfb-maybe
    - npm install
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - ./test.sh
